## Задача 3

### Решение частичной проблемы собственных значений (варианты - 13.8 по методичке (2 и 3 пункты), стр.118, матрицы - 13.9, стр.126).
### Вариант 7

$
A =
\begin{pmatrix}
    -1.00449 & -0.38726 & 0.59047 \\
    -0.38726 & 0.73999 & 0.12519 \\
    0.59047 & 0.12519 & -1.08660
\end{pmatrix}
$

$\epsilon = 0.001$

Входные данные

In [1]:
import numpy as np

A = np.array([
    [-1.00449, -0.38726, 0.59047],
    [-0.38726, 0.73999, 0.12519],
    [0.59047, 0.12519, -1.08660]
], dtype=np.float64)

eps = 0.001

init_vector = np.ones((A.shape[0], 1), dtype=np.float64)


Степенной метод

In [2]:
def power_method(A: np.ndarray, eps: float):
    prev_eig_vector = init_vector.copy()
    eig_vector = A.dot(prev_eig_vector)
    eig_value = eig_vector / prev_eig_vector
    error = None
    count = 0

    while error is None or error > eps:
        count += 1
        prev_eig_vector = eig_vector.copy()
        prev_eig_value = eig_value.copy()

        eig_vector = A.dot(prev_eig_vector)
        eig_value = eig_vector / prev_eig_vector
        error = np.abs(prev_eig_value - eig_value).max()

    eig_vector /= np.linalg.norm(eig_vector, ord='fro')
    print(f"count = {count}\n")
    return eig_vector, eig_value

Результаты полученные степенным методом

In [3]:
eig_vector, eig_value = power_method(A, eps)
print(f"eig_value = {eig_value}")
print(f"eig_vector = \n{eig_vector}\n")
print(f"norm(eig_vector) = {np.linalg.norm(eig_vector, ord='fro')}")


count = 18

eig_value = [[-1.69020274]
 [-1.68996407]
 [-1.69019248]]
eig_vector = 
[[-0.69173072]
 [-0.14665   ]
 [ 0.70710847]]

norm(eig_vector) = 1.0


Проверка на корректность полученных результатов

In [4]:
print(f"A * eig_vector = \n{A.dot(eig_vector)}\n")
print(f"eig_value * eigen_vector = \n{eig_value * eig_vector}")

A * eig_vector = 
[[ 1.16915461]
 [ 0.24788302]
 [-1.19514941]]

eig_value * eigen_vector = 
[[ 1.16916516]
 [ 0.24783323]
 [-1.19514942]]


Метод скалярных произведений

In [5]:
def dot_product_method(A: np.array, eps: float):
    prev_eig_vector = init_vector.copy()
    eig_vector: np.ndarray = A.dot(prev_eig_vector)

    eig_value = eig_vector.transpose().dot(prev_eig_vector)[0, 0] / \
                prev_eig_vector.transpose().dot(prev_eig_vector)[0, 0]

    error = None
    count = 0

    while error is None or error > eps:
        count += 1
        prev_eig_vector = eig_vector.copy()
        prev_eig_value = eig_value

        eig_vector = A.dot(prev_eig_vector)
        eig_value = eig_vector.transpose().dot(prev_eig_vector)[0, 0] / \
                    prev_eig_vector.transpose().dot(prev_eig_vector)[0, 0]
        error = abs(prev_eig_value - eig_value)

    eig_vector /= np.linalg.norm(eig_vector, ord='fro')
    print(f"count = {count}\n")
    return eig_vector, eig_value

Результаты полученные методом скалярных произведений

In [6]:
eig_vector, eig_value = dot_product_method(A, eps ** 2)
print(f"eig_value = {eig_value}")
print(f"eig_vector = \n{eig_vector}\n")
print(f"norm(eig_vector) = {np.linalg.norm(eig_vector, ord='fro')}")


count = 14

eig_value = -1.6901923288085898
eig_vector = 
[[-0.69175397]
 [-0.14654061]
 [ 0.70710841]]

norm(eig_vector) = 1.0


Проверка на корректность полученных результатов

In [7]:
print(f"A * eig_vector = \n{A.dot(eig_vector)}\n")
print(f"eig_value * eigen_vector = \n{eig_value * eig_vector}")

A * eig_vector = 
[[ 1.16913556]
 [ 0.24797296]
 [-1.19514938]]

eig_value * eigen_vector = 
[[ 1.16919725]
 [ 0.24768182]
 [-1.1951492 ]]
